full_warc_prefix: ''

assets_path: pkg://webrecorder/config/assets.yaml

default_coll: ''

default_max_size: 10000000000000

init_import_id: '@INIT'
init_import_user: 'local'
init_import_coll: 'collection'

cdxj_key_templ: 'c:{coll}:cdxj'

max_detect_pages: 0

upload_coll:
    id: 'collection'
    title: 'Collection'
    desc: 'This collection was automatically created from *{filename}*'
    public: true

metadata:
    product: Webrecorder Player
    type: player




